#! /bin/bash

osascript -e 'tell application "iTunes" to if player state is playing then "\n" & name of current track & "\n" & artist of current track & "\n" & album of current track & "\n"'       
exit

